/*
    用于项目MenuID定义
*/
enum CallRecordID
{
	MENU_MAIN_CALLRECORD = 240,

	//CALL RECORD
    MENU_CALLRECORD_ALLCALLS,
    MENU_CALLRECORD_MISSEDCALLS,
    MENU_CALLRECORD_RECEIVEDCALLS,
    MENU_CALLRECORD_DIALLEDCALLS,
    MENU_CALLRECORD_CALLINFO,
    MENU_CALLRECORD_CLEARALL,
};
