#ifndef CLOSE_POS
#define CLOSE_POS

typedef enum CLOSEOUT_STEP_TAG
{
	CLOSEOUT_INIT,
	CLOSEOUT_CONFIRM,
	CLOSEOUT_START_COMM, 
	CLOSEOUT_CONFIRM_COMM,
	CLOSEOUT_SUCCESS,
	CLOSEOUT_PRINT,
	CLOSEOUT_FAIL,
	CLOSEOUT_EXIT
}CLOSEOUT_STEP;

void CT_ClosePOS();

#endif