
/*
    用于项目MenuID定义
*/
enum SMS_MenuID
{
    MENU_MAIN_MESSAGE = 230,
    //MESSAGE
    MENU_MESSAGE_NEW,
    MENU_MESSAGE_INBOX,
    MENU_MESSAGE_OUTBOX,
    MENU_MESSAGE_SENT,
    MENU_MESSAGE_DRAFT,
    MENU_MESSAGE_MSGSETTINGS,
    MENU_MESSAGE_CLEAR,

    MENU_MSGSETTINGS_MSGCENTRE,
    MENU_MSGSETTINGS_SAVESMSTO,
};


